### ISSUE TITLE
Integration to GTK +

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/GameHub#12]
<div align=center>

![captura de tela de 2018-07-15 10-46-10](https://user-images.githubusercontent.com/26097419/42734629-b32fe12e-881d-11e8-8ebf-60d6c23bc0b0.png)

</div>

**Comment by tkashkin** [comment]
@LeandroStanger What's the problem exactly? Are you using flatpak version on some non-elementary distro and app is using elementary theme? I've tried it on a few distros and haven't noticed that. Flatpak version is based on [elementary BaseApp](https://github.com/flathub/io.elementary.Loki.BaseApp/blob/master/io.elementary.Loki.BaseApp.json#L64) so that might be a problem.

**Comment by LeandroStanger** [comment]
@tkashkin I use Endless OS
I wanted an option to put the buttons on the right side of the screen 
<div align=center>

![captura de tela de 2018-07-15 10-46-10](https://user-images.githubusercontent.com/26097419/42734629-b32fe12e-881d-11e8-8ebf-60d6c23bc0b0.png)

</div>
The application is very beautiful

**Comment by tkashkin** [comment]
@LeandroStanger I'm still not sure what are you talking about.

Here it is (flatpak version) running on Endless OS live session with default settings.

![image](https://user-images.githubusercontent.com/2003017/42738663-ed1379c4-888f-11e8-9f6c-8030d31be61f.png)

**Comment by LeandroStanger** [comment]
@tkashkin Could you send me the flatpak for me to test?

**Comment by tkashkin** [comment]
@LeandroStanger https://github.com/tkashkin/GameHub/releases/tag/0.5.3

**Comment by LeandroStanger** [comment]
Now it's working
