### ISSUE TITLE
Flatpak: Localizations are not working

### ISSUE THREAD

**Issue by LeandroStanger** [tkashkin/GameHub#13]

**Comment by tkashkin** [comment]
@LeandroStanger flatpak bundles [can not include extensions now](https://github.com/flatpak/flatpak/issues/165), it must be built locally and/or installed from repo.

But for some reason locales are broken in flatpak version of GameHub. I think something is wrong with locale paths.

**Comment by LeandroStanger** [comment]
This has not been fixed GameHub 0.5.4

**Comment by tkashkin** [comment]
@LeandroStanger It should be fixed in [0.5.7](https://github.com/tkashkin/GameHub/releases/tag/0.5.7), however it will probably not work if you install it from bundle.

It should work if you build it yourself and install from local repo. Manifest and instructions: https://github.com/tkashkin/GameHub/tree/flatpak

**Comment by LeandroStanger** [comment]
- Add option to change language in GameHub settings

**Comment by tkashkin** [comment]
@LeandroStanger, @cho2, there were a few strings added, please check if Google Translate translated them correctly.
