### ISSUE TITLE
Import already install wine games WINEPREFIX

### ISSUE THREAD

**Issue by frstrikerman** [tkashkin/GameHub#160]
As for now gamehub is missing an helper to install wine games like PlayOnLinux or lutris.
But as a nicer GUI and support for gog achievement so it might be useful to be able to import custom WINEPREFIX and not just the install directory and the game

**Comment by lewellyn** [comment]
I came trawling the Issues for this very thing. I have some (non-GOG) games I installed (from CD-ROM) into their own WINEPREFIXes prior to learning about GameHub.

I cannot figure out how to define the WINEPREFIX to use for launching the games, and I can't get a custom script to work (customs scripts seem to be poorly documented, plus my Exectuable field keeps clearing, presumably because I'm doing something wrong).

Additionally, trying to reinstall doesn't yield any useful output to the console, nor do the games install. So I can't just wipe their prefixes and move them to GameHub.

So, being able to use already installed games is extremely valuable to me. In the mean time, I still keep their icons on my desktop to run outside of GameHub.

I see that the commit supposedly added support for this, but I simply can't see how to do it in the UI.

**Comment by tkashkin** [comment]
@lewellyn

> I cannot figure out how to define the WINEPREFIX to use for launching the games

It's currently implemented as a CompatTool option. Default is `<game_dir>/_gamehub/compat/<tool_id>`. You can change it in run dialog (right click in list/grid/details title):

![image](https://user-images.githubusercontent.com/2003017/55745123-2f07f180-5a3f-11e9-99dd-bafda5a22723.png)

> I can't get a custom script to work (customs scripts seem to be poorly documented.

"Custom script" tool just executes your shell script and passes some variables to it. These variables are named in default script template.

> plus my Exectuable field keeps clearing, presumably because I'm doing something wrong

It shouldn't, unless there's a bug I don't know about. Try to press Enter after selecting an executable.

**Comment by lewellyn** [comment]
As a concrete example, let's use the [Pokemon TCG](https://www.pokemon.com/us/pokemon-tcg/), as it's freely downloadable and exhibits the behaviors I note.

When I add it using the +, and then open the Properties, I go through and set all the options appropriately, to the best of my ability.

![image](https://user-images.githubusercontent.com/658826/55746183-209de380-5a07-11e9-934f-923f0427678a.png)

I see no options for a Proton prefix, though I selected Proton manually (changed from Custom Script).

After I close the window (hitting Enter on each field, for good measure, as you suggested), the Properties window doesn't retain all my information selected and still has no place for a WINEPREFIX. (Though it does retain the Image of all the data I input, strangely.)

![image](https://user-images.githubusercontent.com/658826/55746303-5b078080-5a07-11e9-9882-7d9815c699ee.png)

The Details window, sadly, does not have anything except an Install button (which doesn't seem to actually do anything other than hang the app for a moment) and a Properties button. It also shows as a Linux game rather than a Windows game.

![image](https://user-images.githubusercontent.com/658826/55746543-eb45c580-5a07-11e9-879d-6137416cac59.png)

Hopefully the screenshots help illustrate the flow I'm expecting should work (which may be wrong?) and help convey my desires and expectations better. :) (And please don't mind my retro GUI theme... I could re-take the screenshots with Adwaita, but the functionality does not change.)

**Comment by tkashkin** [comment]
@lewellyn executable path should be Unix-style, not Windows-style. `/` instead of `\`.

It works fine for me:

![image](https://user-images.githubusercontent.com/2003017/55747596-41852980-5a45-11e9-8902-1dbfa8a5a433.png)

**Comment by lewellyn** [comment]
But where do I put the WINEPREFIX, which is the question in this issue? :)

**Comment by tkashkin** [comment]
@lewellyn set executable correctly first. Game will have installed state when executable is correct and exists. 
![image](https://user-images.githubusercontent.com/2003017/55747851-e6076b80-5a45-11e9-88c1-9de04abcc6a0.png)

**Comment by lewellyn** [comment]
I must be doing something completely wrong. I set the executable to `/home/lewellyn/.local/share/wineprefixes/Pokemon-TCGO/drive_c/users/lewellyn/Application Data/Pokémon Trading Card Game Online/PokemonTradingCardGameOnline/Pokemon Trading Card Game Online.exe` which is the insane path to the windows binary, on disk. I tried selecting it in the picker. Neither gets the executable saved, and therefore none of the extra behaviors you mentioned. :(

The only message I see in the console is `(com.github.tkashkin.gamehub:15836): Gtk-WARNING **: 14:38:37.303: gtk_window_set_titlebar() called on a realized window` which I see extremely often during other normal use and I assume is unrelated to this.

**Comment by tkashkin** [comment]
> The only message I see in the console is (com.github.tkashkin.gamehub:15836): Gtk-WARNING **: 14:38:37.303: gtk_window_set_titlebar() called on a realized window which I see extremely often during other normal use and I assume is unrelated to this.

Yes, it's unrelated.

I have tested it with a very long path and it still works correctly:
```
[DEBUG]  [Utils.run] {'/mnt/LinuxStorage/SteamLibrary/steamapps/common/Proton 4.2/proton' 'run' '/mnt/LinuxStorage/Games/User/test/verylongpath/wqeqweqtewrgdfgd/dsgdsgdfsgfdbfdnbdfgnfgdnfgtnfg/rehredernernren/test/verylongpath/wqeqweqtewrgdfgd/dsgdsgdfsgfdbfdnbdfgnfgdnfgtnfg/rehredernernren/Pokémon Trading Card Game Online/Pokemon Trading Card Game Online.exe'}; dir: '/mnt/LinuxStorage/Games/User/test/verylongpath/wqeqweqtewrgdfgd/dsgdsgdfsgfdbfdnbdfgnfgdnfgtnfg/rehredernernren/test/verylongpath/wqeqweqtewrgdfgd/dsgdsgdfsgfdbfdnbdfgnfgdnfgtnfg/rehredernernren/Pokémon Trading Card Game Online'
```

Try to remove it from GameHub and readd. Click Add game, select executable with picker and it should fill game directory field automatically. Then confirm adding and try to run it.

**Comment by lewellyn** [comment]
Re-adding via the picker gets me closer (it feels like there's a bug somewhere that I was hitting, no?), but still no way to specify the WINEPREFIX to use. I simply cannot find that window you posted with the prefix and environment variables. I deleted and re-added eight games, all with the same outcome, so I'm not sure what I'm doing wrong. :(

![image](https://user-images.githubusercontent.com/658826/55749548-2dbed080-5a0f-11e9-8a23-d4a4de49ee3f.png)

![image](https://user-images.githubusercontent.com/658826/55749601-521aad00-5a0f-11e9-9338-7f82fc35978f.png)

**Comment by tkashkin** [comment]
> I simply cannot find that window you posted with the prefix and environment variables

Press "Run with compatibility layer" button and it will show this dialog first time. If you need to change something later, open it from context menu.

**Comment by lewellyn** [comment]
Aha! I can't say that was very obvious, but it's repeatable! :dancer: 

Do you mind if I add a wiki page with the directions, for the benefit of others looking for how to make this happen? (And I'll use a standard theme for screenshots, of course.)

I guess this issue is ripe for closing since it has everything needed for a future spelunker to get their own already-installed games put into GameHub. :D

**Comment by tkashkin** [comment]
> Do you mind if I add a wiki page with the directions, for the benefit of others looking for how to make this happen? (And I'll use a standard theme for screenshots, of course.)

Sure, why not? It can be useful for new users. Let me know if you encounter something not obvious.

**Comment by Lucki** [comment]
Wow, this is really hidden, I didn't even know I could get this prefix setting window show up a second time…
I suggest to rename the context menu option as it is called the same as the other button but is doing something completely different. I thought it is doing exactly the same and didn't even tried to use the context menu entry.

![Bildschirmfoto-20190408235157-377x209](https://user-images.githubusercontent.com/1408843/55759349-65eb0100-5a59-11e9-840e-a2e082b5751a.png)

**Comment by tkashkin** [comment]
@Lucki 

> Wow, this is really hidden, I didn't even know I could get this prefix setting window show up a second time…
I suggest to rename the context menu option as it is called the same as the other button but is doing something completely different. I thought it is doing exactly the same and didn't even tried to use the context menu entry.

Button and menu option are same, but dialog shows only for the first time if opened with button.

The idea is that you configure it once and then launch game instantly by clicking button or grid card. If you need to change compatibility options, open dialog from menu explicitly. It may be not so obvious, but I couldn't think about better solution.

> I suggest to rename the context menu option

Any specific suggestions?

> Edit: Can I open the same window for custom emulator? There's no context menu available for them.

Currently there's no way to open it explicitly. It will show before first emulator launch. I may add a button somewhere.

**Comment by lewellyn** [comment]
> > I suggest to rename the context menu option
> 
> Any specific suggestions?
> 

"Configure compatibility layer" would probably save some confusion all around. Just my two cents, plus or minus inflation. I expect that should translate into the supported languages fairly well, too.

**Comment by Lucki** [comment]
> Any specific suggestions?

Maybe _Configure and run_.

**Comment by lewellyn** [comment]
I think part of the problem with "Configure and run" is that it is less obvious that just closing the window without running will save the configuration options. I expect most people aren't right-clicking to run things (I'd hope, at least!), so the Run button on the resultant dialog strikes me more as a "bonus" than the required way to execute.

**Comment by Lucki** [comment]
Yea, good point. But I honestly I would expect that settings window to be accessible in the compatibility section in the game properties and that context menu entry to just do the same as the button.

**Comment by lewellyn** [comment]
I would be inclined to agree. Hiding it in a context menu is less discoverable than putting it in the Properties.

This is my mockup of how I'd expect the Properties window to look (with no changes to the configuration window). This would allow removal of the confusing menu option altogether, making for a cleaner and more intuitive UI. :)

![image](https://user-images.githubusercontent.com/658826/55763335-7d63c300-5a34-11e9-8edb-a3ea996b7420.png)
