### ISSUE TITLE
GameHub can't integrate with Steam

### ISSUE THREAD

**Issue by pyroxar** [tkashkin/GameHub#185]
###### Expected behavior
GameHub should can integrete with Steam when Steam is installed from flathub.

###### Actual behavior
GameHub can't integrate with Steam when Steam is installed from flathub.

Steam is detected:
![obraz](https://user-images.githubusercontent.com/23406555/51977965-1dc3c700-2489-11e9-9c40-78436f4bb366.png)
When i click then Steam is staring but GameHub do nothing more.

###### Steps to reproduce
Install Steam form flathub.

###### Version and environment

```
I run GameHub wth terminal: flatpak run com.github.tkashkin.gamehub
[INFO]   Version: 0.13.1-1f713f3-master
[INFO]   Branch:  master
[INFO]   Commit:  1f713f3 (1f713f3f3d13385833106c9fc8a9cfccafc0a52b)
[INFO]   Distro:  flatpak
[INFO]   DE:      X-Cinnamon

Flatpak 1.0.1
Linux Mint 19.1
```

**Comment by tkashkin** [comment]
Make sure Steam path in settings is correct.

**Comment by psycho-driver** [comment]
I'm having the same problem.  Steam path in settings is correct.  It detects that steam is installed but it doesn't think I'm authenticated.

**Comment by psycho-driver** [comment]
Aha, not a problem with GameHub.  The symbolic links in ~/.var/app/com.valvesoftware.Steam/.steam were wrong by default (pointing to where steam normally would live in my user's directory structure under ~/.local/share/Steam.  GameHub picked it up after I corrected these, so it's a flatpak Steam problem.

**Comment by Saroufim** [comment]
It's probably this issue: https://github.com/flatpak/xdg-desktop-portal/issues/306

**Comment by kakolisgay** [comment]
Having the same issue, flatpak steam is installed and running but Gamehub doesn't detect it

**Comment by RTSAjwad** [comment]
Same issue here using app image gamehub. Funnily enough it is detected through gnome games.

**Comment by VelocityIsntSpeed** [comment]
I was having this problem. I fixed it by setting in GameHub's settings the Steam installation directory path to `~/.var/app/com.valvesoftware.Steam/.steam` (note the `.steam` folder at the end).

The default was `~/.steam`, which doesn't exist (i have the flatpak steam installed). GameHub said Steam was not installed.

First i tried changing it to `~/.var/app/com.valvesoftware.Steam/`, which made GameHub say that Steam is installed, but not authenticated. IIRC it even automatically launched Steam, which logged in automatically, since i had already done so days ago. But GameHub just kept telling me in the initial set-up screen to login in Steam then come back.

Error messages are sorely missing here. GameHub should say "Steam installation directory not found" and stuff like that. And it should automatically look for the Flatpak version of Steam too.
