### ISSUE TITLE
Mintinstall can't be run from app chooser from flatpak.

### ISSUE THREAD

**Issue by pyroxar** [tkashkin/GameHub#186]
###### Expected behavior
When i clicked green link "Software manager" then on the Linux Mint should be open mintinstall, not Gnome Software.

###### Actual behavior
When I clicked green link "Software manager"  on the Linux Mint, GameHub try to open Gnome Software but showed up a error.

The button "OK" can't be clicked and close window (window with error) button don''t close up window.

###### Steps to reproduce
Try to click green link "Software manager" on the Linux Mint 19.1

###### Version and environment

```
[INFO]   Version: 0.13.1-1f713f3-master
[INFO]   Branch:  master
[INFO]   Commit:  1f713f3 (1f713f3f3d13385833106c9fc8a9cfccafc0a52b)
[INFO]   Distro:  flatpak
[INFO]   DE:      X-Cinnamon
```
https://github.com/linuxmint/mintinstall/issues/236

**Comment by friday** [comment]
Is it possible to detect this from the desktop environment? As far as I know there's no environment variable or setting for it in Gnome under Default apps (see attached picture). Some DE's don't have graphic software managers at all. Arch for example doesn't officially have one.

![screenshot from 2019-01-30 16-29-13](https://user-images.githubusercontent.com/515120/51992007-8a9c8880-24ac-11e9-9bed-08d45b76fd59.png)

**Comment by friday** [comment]
Rewritten answer (I hadn't quite understood what you were trying to do before, so I removed the comment):

> When i clicked green link "Software manager"

Where did you see this and what were you trying to do when you clicked it? Judging by https://github.com/linuxmint/mintinstall/issues/236 it seems like you tried "Open with" and then picked the application named "Software manager". In that case it has nothing to do with GameHub. It's just did what you asked it to do, which is seemingly not supported.

The view (below) is the Gnome/GTK view for opening an unknown file. Maybe your screenshot in https://github.com/linuxmint/mintinstall/issues/236 is the Linux Mint version of this view? I can't tell since I don't speak Polish.

![screenshot from 2019-01-30 16-45-44](https://user-images.githubusercontent.com/515120/51993128-883b2e00-24ae-11e9-99d1-86e0b09c4677.png)

I also don't think it's possible to detect software manager from the desktop environment. As far as I know there's no environment variable or setting for it in Gnome under Default apps. Some DE's don't have graphic software managers at all. Arch for example doesn't officially have one.

**Comment by pyroxar** [comment]
Linux Mint version of the view above:
![obraz](https://user-images.githubusercontent.com/23406555/51994508-37790480-24b1-11e9-9eaf-0dbca541db46.png)

**Comment by friday** [comment]
Alright. It still looks like some kind of an appchooser view. Perhaps for flatpak or custom URI protocols. It's not something in GameHub's gui based on what I've seen and searching the code and translations.

**Comment by tkashkin** [comment]
This dialog shows when user tries to open an external URL from any flatpak app.

In this case you are trying to open Steam client via `steam://` URL protocol and flatpak portal shows you app chooser.
App chooser has an option to open a software center to install apps that can handle this URL protocol.

I guess you should report it to [flatpak/xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk).
