### ISSUE TITLE
Add 'about' section to settings for easy reference and linking

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#212]
Add an 'about' section to the settings section to make it easier to see version number of GameHub along with links to GameHub's website and GitHub.

**Comment by tkashkin** [comment]
I can add a generic [GTK AboutDialog](https://valadoc.org/gtk+-3.0/Gtk.AboutDialog.html), but:
* I have no idea where to put it. GNOME apps have an app menu, but there's no such menu in GameHub
* I'm not sure if it's really necessary to have this dialog

###### Why there's no About dialog now?

GameHub was initially started as an elementary OS application and was meant to be distributed primarily through elementary AppCenter.

It's built on GTK and Granite and follows mostly elementary HIG instead of GNOME HIG.

elementary apps do not have About dialogs and [Granite AboutDialog is deprecated](https://valadoc.org/granite/Granite.Widgets.AboutDialog.html). All of app's metadata is meant to be shown by application managers like AppCenter or GNOME Software. More in [this post](https://medium.com/elementaryos/peace-out-about-dialogs-8efa956c0562).

**Comment by trprado** [comment]
A possibility is to add a new tab in the config with the about info. I liked the idea, and if possible put version information of app.

**Comment by tkashkin** [comment]
I have tried both `Gtk.AboutDialog` and `Granite.AboutDialog` and I don't like neither of those.

I have decided to create a custom About dialog. Here's how it looks now:
![image](https://user-images.githubusercontent.com/2003017/55269403-a8674d80-52a3-11e9-9530-f879d5c97366.png)

Do you have any feedback, did I forget to add anything important?

Also I still have no idea where to put a button to open this dialog.

**Comment by neuromancer** [comment]
Feedback: if you want, don't forget to add you as the author of this wonderful software.
Regarding where to put this, you could make the "GameHub" title in the top-center main window clickable to open this dialog.

**Comment by tkashkin** [comment]
About dialog is implemented in latest commit. Issue templates are updated to mention about dialog.
