### ISSUE TITLE
Queue installing games

### ISSUE THREAD

**Issue by glaere** [tkashkin/GameHub#220]
Current behaviour is multiple games that are installing will install concurrently. This can seriously slow down your system. It would be better if installs are queued.

Maybe use the download icon for both downloading and install/queueing progress?

**Comment by tkashkin** [comment]
Do you have any ideas how to implement it?

I don't want to add another switch in settings for such features since settings are already quite cluttered.
Should this queue be sortable?

Right now you can manually pause downloads and resume them at any time.

**Comment by neuromancer** [comment]
You could simply block game installations if there is another one already runing.

**Comment by lewellyn** [comment]
Indeed. There isn't much reason for a toggle in the settings. Steam, for instance, doesn't let you download and install multiple games at once, and no one complains much about that. :+1: 

If anything, there should be a toggle in the settings to limit number of simultaneous downloads, for those on poor connections who end up with "Download failed" on all but a couple, necessitating a restart of the app. Since there isn't, I can't see any justification for adding one to allow "please spam my CPU and/or disk with multiple simultaneous installers please!" :rofl:

**Comment by tkashkin** [comment]
Installer downloads are queued in 87c7f3d. I'm sure it's more broken than it was so testing is needed.

**Comment by tkashkin** [comment]
Closing. Reopen of there are any related issues.
