### ISSUE TITLE
Request for an RPM package for fedora, CentOS

### ISSUE THREAD

**Issue by jatin-cbs** [tkashkin/GameHub#230]
It will be great to have an RPM package for fedora, CentOS, openSUSE. They have one of the largest communities in linux.

**Comment by tkashkin** [comment]
* There is an OpenMandriva RPM package [here](https://github.com/tkashkin/GameHub/issues/156#issuecomment-477256108). I have no idea if/how it can be used on other RPM distros, but at least you should be able to reuse its [spec](https://github.com/OpenMandrivaAssociation/gamehub) to build a package for your distro.
* There was a discussion about fedora packages: #156, #115.

**Comment by lewellyn** [comment]
There is also a package that I've been using on openSUSE Tumbleweed [available on OBS](https://build.opensuse.org/package/show/home:malkavi/gamehub). I haven't investigated the build failures for other openSUSE versions.

But if @tkashkin would like to have autogenerated RPMs and DEBs for everything sensible to support (which probably means ix86/x86_64 only, and on potentially everything reasonably current except Mageia since that is a difficult target with little general gain especially since there's an OpenMandriva RPM), I'll gladly package up GameHub under my home OBS project and get it working everywhere I can. Rebuilds would be able to be triggered by commits, via a webhook. It's the rebuild part that makes me not want to tackle it unless there was a webhook in place. :)

In theory, AppImage and Arch are valid OBS targets as well, but I haven't had much luck with getting those working yet. I'm always up to try again! :)

**Comment by tkashkin** [comment]
@lewellyn that would be great. I have tried to setup OBS but I have no experience with RPM distros.

I don't think that debs and AppImages are necessary since both are already built on each commit (as well as flatpaks). Arch is also not necessary because it's already in AUR.

**Comment by tkashkin** [comment]
Closing this issue in favor of #156.

**Comment by tim77** [comment]
https://github.com/tkashkin/GameHub/issues/234
