### ISSUE TITLE
Flatpak installation not working.

### ISSUE THREAD

**Issue by jatin-cbs** [tkashkin/GameHub#231]
installing flatpak falis on all distros. (flatpaks are not distro specific ofcourse).
![Screenshot from 2019-04-02 15-30-54](https://user-images.githubusercontent.com/40650341/55394255-83e9ca80-555c-11e9-9dd0-8686c3a0009c.png)

**Comment by jatin-cbs** [comment]
I cant see any other way of getting it installed on fedora or any RPM based distro, 
git may work but dependencies are not even mentioned for it only debian deps are listed and flatpak not installing.

**Comment by tkashkin** [comment]
> installing flatpak falis on all distros. (flatpaks are not distro specific ofcourse).

* Why are you trying to build a flatpak yourself instead of downloading a [prebuilt flatpak bundle](https://github.com/tkashkin/GameHub/releases) and installing it with `flatpak install GameHub-*.flatpak`?
* Your build fails because dependencies are not installed due to `503: Service Unavailable` from flathub. Try again later.

> I cant see any other way of getting it installed on fedora or any RPM based distro

* There is an OpenMandriva RPM package [here](https://github.com/tkashkin/GameHub/issues/156#issuecomment-477256108). I have no idea if/how it can be used on other RPM distros, but at least you should be able to reuse its [spec](https://github.com/OpenMandrivaAssociation/gamehub) to build a package for your distro.
* There was a discussion about fedora packages: #156, #115.
