### ISSUE TITLE
All my custom games have upgrades available?

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#238]
In the latest `dev` revision, all my custom games are marked to have upgrades available (shown with the small white dot in one corner):

![game](https://user-images.githubusercontent.com/110782/56058054-c9fe1580-5d36-11e9-9132-84a86a5b5030.png)

**Comment by neuromancer** [comment]
Also, even GOG games that are re-downloaded and reinstalled will have the same dot (e.g. Dungeon Keeper)

**Comment by tkashkin** [comment]
> In the latest dev revision, all my custom games are marked to have upgrades available (shown with the small white dot in one corner):

That was fixed.

> Also, even GOG games that are re-downloaded and reinstalled will have the same dot (e.g. Dungeon Keeper)

I'm not sure how to fix that because I don't know what exactly does this flag mean and when does GOG set/reset it.

---

There's another problem with GOG updates I'm not sure how to fix.

Currently game info is cached to db and is not refreshed. That's fine if info doesn't change. Currently there's no way for user to force refresh game info except manually removing it from db.

Updates flag could be useful for automatic refresh, but there should be a way to reset this flag on GOG API side for it to work.
