### ISSUE TITLE
Steam overlay not working in Steam games launched using Gamehub

### ISSUE THREAD

**Issue by Kabouik** [tkashkin/GameHub#286]
The Shift+Tab Steam overlay does not show up when running Steam games from Gamehub, and the F12 screenshots do not work. Is there a way to enable them when running games from Gamehub, since Steam is launched in the background anyway when running Steam games?

**Comment by tkashkin** [comment]
That's weird, it works for me. I've tried it on Ubuntu 19.10 and on Solus (both repo package and AppImage).

**Comment by Kabouik** [comment]
Sorry I made you test all this, it never worked for me so I was pretty sure the overlay was just not triggered by Gamehub. It turns out it has stopped working on my computer (even with Steam) since a few weeks, exactly when I started using Gamehub, hence the confusion. I think it was related to LSI and the native libraries that I had to disable a few weeks ago when Steam stopped working with them. Sorry for the noise.

**Comment by buxel** [comment]
I stumbled upon this issue since i have a very similar one using Lutris. I'm not using LSI, tough.
I just verified that the steam overlay does not work for me when adding a GameHub game to steam.

I added the the Game "Minit" to GameHub and clicked "add to steam" in the properties. The game launches trough steam but the steam overlay is not working.

Maybe some cross-examination can shed some light on this.
