### ISSUE TITLE
Edit lauch command

### ISSUE THREAD

**Issue by MagicRB** [tkashkin/GameHub#297]
I'd like to be able to edit the command GameHub uses to launch my game. So instead of "WINEPREFIX=/whatever wine whatever.exe" i'd like to wrap that whole thing in another command, for example "gamemoderun 'WINEPREFIX=/whatever wine whatever.exe'". If this is already possible, I'm sorry for opening this issue. Thx

**Comment by tkashkin** [comment]
You can use "Custom script" compatibility layer instead of Wine to achieve this.

GameHub will run this script instead of running game.
Builtin Wine integration will not be used in this case and you can do anything you want in script.

GameHub will pass some arguments to this script. Default script template uses these arguments:
```bash
#!/bin/bash
GH_EXECUTABLE="$1"
GH_INSTALL_DIR="$2"
GH_GAME_ID="$3"
GH_GAME_ID_FULL="$4"
GH_GAME_NAME="$5"
GH_GAME_NAME_ESCAPED="$6"
```

If you want to use it for multiple games, you can create a "Custom emulator" that will use script itself.

**Comment by MagicRB** [comment]
Thx! Tho i have another issue related, the window won't open, i click "Edit Script" and nothing happens. I'm using KDE if that makes a difference. And I'm on Arch

**Comment by tkashkin** [comment]
It should be opened in default text editor, but it's possible that it tries to run script instead of editing it.
You can manually edit `_gamehub/customscript.sh` in game's install directory.

**Comment by MagicRB** [comment]
That works, but it kind of beats the point of a game launcher. It would be much better if you GameHub provided me with a way to edit the launch command like steam does

**Comment by tkashkin** [comment]
Yes, it can be improved. I'll think how can it be implemented.

**Comment by MagicRB** [comment]
Thx. I'll close this now

**Comment by tkashkin** [comment]
@MagicRB since 075168a you can edit game's arguments and override launch command like possible in Steam.

By default game args will be appended at the end of default launch command.
If args contain `${command}` or `$command` variable, it will be replaced with default command.

It should work for most compatibility layers if I haven't missed something. Let me know if something is wrong.

**Comment by RilicTheFox** [comment]
How can run you separate commands after using $command? I've tried `$command; separate-command-here` but it isn't working.
