### ISSUE TITLE
Enable D9VK from the Proton compability layer options

### ISSUE THREAD

**Issue by neuromancer** [tkashkin/GameHub#307]
Latest release of Proton include [D9VK support](https://github.com/ValveSoftware/Proton#runtime-config-options) to optionally to improve the performance of DirectX9 games. I wonder if we can have a dedicated checkbox in the Proton compatibility options to quickly enable this for each game.

**Comment by btegs** [comment]
Sorry to bring up an old issue, but is this planned for an upcoming -dev release? D9VK has been seeing a lot of traction the past few months and it would be nice to add it as an option.

**Comment by tkashkin** [comment]
I don't have much free time to maintain GameHub right now and I'm not sure how much time will I have in near future.
I'll try to fix some bugs, merge PRs and possibly start implementing UI changes (#304), but I can't say when will it happen.

**Comment by btegs** [comment]
@tkashkin - Sorry to hear about that. The project has a lot of potential and some of us have loved using it during this time. At this point, I cannot imagine NOT using it and it would be unfortunate if you gave up on it.

This brings to light a lot of issues developers have with free software: it gets really popular and once people have started loving it, the developer stops updating it due to "real life issues" and then it gets abandoned.

**Comment by tkashkin** [comment]
#312 is merged in `dev`. I'll probably merge `dev` into `master` later today.

**Comment by btegs** [comment]
@tkashkin - Just pulled the latest version down from the PPA. Thanks!!!
