### ISSUE TITLE
[Feature Request] Add option for RADV ACO command and remove D9VK command

### ISSUE THREAD

**Issue by btegs** [tkashkin/GameHub#347]
Since you have other predefined startup commands for GameHub, why not add the one to enable the ACO compiler for RADV users? It is:

```
RADV_PERFTEST=aco
```
and can replace the D9VK option with this since the PROTON_USE_D9VK=1 command is irrelevant in Proton 5.0.

**Comment by tkashkin** [comment]
I'm not experienced with AMD-specific options as I don't have any AMD hardware.

It would help if you sent a PR with this tweak to https://github.com/tkashkin/GameHub/tree/dev/data/share/tweaks.

I'm also not sure about removing `PROTON_USE_D9VK=1` tweak. It might be better to specify exact Proton versions it can be applied to instead of fully removing it.

**Comment by Lucki** [comment]
> specify exact Proton versions it can be applied to

It's **only** supported in 4.11. Since 5.0 it's turned on by default and can be disabled with the same switch DXVK uses: `PROTON_USE_WINED3D`

**Comment by btegs** [comment]
I made a pull request via https://github.com/tkashkin/GameHub/pull/348 and I wanted to check with @tkashkin if this is the best method. I created an amd.json file for AMD related tweaks.
