### ISSUE TITLE
Remove steam account/multiple steam accounts

### ISSUE THREAD

**Issue by KydZombie** [tkashkin/GameHub#389]
I have 2 steam accounts, I logged into one of them to enable family sharing. Once I switched over to my main account, I added steam to gamehub. Gamehub **should** take the account I am currently using, and potentially allow me to add both. If it doesn't work, it should at least allow me to either A: remove the steam account currently used on it, or B: add a 2nd account to gamehub. I am unable to use gamehub properly as only _some_ of my game library is available in gamehub now.

**Comment by jarrard** [comment]
Yeah I have this same issue. You can rearrange /home/theriddick/.steam/steam/config/loginusers.vdf to have the accounts around different but it may still try to detect the privacy setting of other account so be sure BOTH accounts are set to public privacy because you can't use multiple steam accounts with gamehub atm which is a damn shame.
