### ISSUE TITLE
"Open installation directory" opens VS Code instead of Dolphin

### ISSUE THREAD

**Issue by WorldTeacher** [tkashkin/GameHub#668]
###### Expected behavior

clicking "Open installation directory" should open default File Manager instead of VS Code

###### Actual behavior

it opens the installation directory in VS Code

###### Steps to reproduce

1. click "open installation directory"
2. (probably be me)
3. see it happen 

###### Version and environment
```
- GameHub
    Version: 0.16.3-9327885-makepkg
    Branch:  makepkg
    Commit:  9327885393f022fd1cccb219a19c0f87ae5e0f5a
- Environment
    Distro:  XeroLinux
    DE:      KDE
    GTK:     3.24.36
```

**Comment by JustinTJones** [comment]
I had this problem too and it turned out to be caused by the default file associations set by my desktop environment. I had to to tell my desktop environment to open `directory` with my file manager instead of VS Code. 

This is not the fault of GameHub, it's actually the fault of VS Code, which modifies default file associations upon install.

Assuming that you're using KDE Plasma based on your reference of Dolphin, see this article for help changing that on KDE Plasma: https://userbase.kde.org/System_Settings/File_Associations/en

**Comment by WorldTeacher** [comment]
this fixed it, thanks

> Assuming that you're using KDE Plasma based on your reference of Dolphin, see this article for help changing that on KDE Plasma: https://userbase.kde.org/System_Settings/File_Associations/en

**Comment by JustinTJones** [comment]
You're welcome!
