### ISSUE TITLE
How to use Gamehub

### ISSUE THREAD

**Issue by afettouhi** [tkashkin/GameHub#97]
I just started using Gamehub and I wanted to install a game from GOG library. More specifically I wanted to install Shadow Warrior 2 which of course is windows only. I am a bit confused by the installation options for Gamehub. When I click the game I get a popup telling me how to install the game. I can choose different compatibility layers such as Innoextract, Wine (wine64) and Wine (wine). I am unsure on what to choose here. The installer for the game consists of 5 different exe files plus 3 patch files. So what do I choose here for compatibility layer?

**Comment by tkashkin** [comment]
Compatibility layers allow to install or run non-native games. For each tool to be usable some software needs to be installed.

###### Install tools:
* Innoextract - requires [`innoextract`](http://constexpr.org/innoextract/), allows to extract GOG installers.
* Wine - requires `wine`, allows to get game files from installer by actually running it.
* Proton - requires `Steam` and `Steam Play/Proton`, same as Wine.

###### Run tools:
* Wine
* Proton
* DOSBox - requires `dosbox`
* "Custom script" - starts custom shell script instead of game

You can select any tool at any time for both installation and launch.

For GOG installers `innoextract` is preferred, because it extracts game without actually executing any installer code.

Game installer files will be downloaded once regardless of compat layer selected. You can retry installation later with another tool without redownloading files.

---

If some layers are shown as available, but you don't have corresponding software installed, make sure you are using latest GameHub version (try `dev` branch).

**Comment by afettouhi** [comment]
Thanks for the clarification I got it running.
